In [ ]:
# Array is a data structure that stores values of same data type in python the main difference between arrays and lists
# for arrys we have to import the library

In [3]:
import numpy as np
lst=[1,2,3,4,5]
arr=np.array(lst)
print(arr)

[1 2 3 4 5]


In [5]:
type(arr)

numpy.ndarray

In [7]:
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[3,4,5,6,7]
arr=np.array([list1,list2,list3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [9]:
arr.shape

(3, 5)

In [11]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [13]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [21]:
print(arr[0:,1])

[2 3 4]


In [31]:
print(arr[:4,3])

[4 5 6]


In [35]:
print(arr[1:,1:3])

[[3 4]
 [4 5]]


In [37]:
print(arr[2:,2])

[5]


In [43]:
print(arr[1:,2:4])

[[4 5]
 [5 6]]


In [45]:
print(arr[1:,2:5])

[[4 5 6]
 [5 6 7]]


In [47]:
print(arr[0:,0:3,])

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [51]:
print(arr[0:,0::4])

[[1 5]
 [2 6]
 [3 7]]


In [53]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [57]:
print(arr[0:,[0,4]])

[[1 5]
 [2 6]
 [3 7]]


In [59]:
print(arr[:,::4])

[[1 5]
 [2 6]
 [3 7]]


In [65]:
import numpy as np
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [67]:
arr1=arr*arr
print(arr1)

[[ 1  4  9 16 25]
 [ 4  9 16 25 36]
 [ 9 16 25 36 49]]


In [69]:
arr2=arr*2
print(arr2)

[[ 2  4  6  8 10]
 [ 4  6  8 10 12]
 [ 6  8 10 12 14]]


In [83]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [85]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Practice 

In [13]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [15]:
arr=np.array([10,20,30,40,55,60])
arr

array([10, 20, 30, 40, 55, 60])

In [17]:
arr.reshape(2,3)

array([[10, 20, 30],
       [40, 55, 60]])

In [19]:
arr.reshape(3,2)

array([[10, 20],
       [30, 40],
       [55, 60]])

In [51]:
# 1d array user input
list1=[]
n=int(input("Enter the number of elements in list : "))
for _ in range(n):
    a=int(input("Enter the value of list element :"))
    list1.append(a)
arr=np.array(list1)
print(arr)
arr.reshape(2,3)

Enter the number of elements in list :  6
Enter the value of list element : 1
Enter the value of list element : 2
Enter the value of list element : 3
Enter the value of list element : 4
Enter the value of list element : 5
Enter the value of list element : 6


[1 2 3 4 5 6]


array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [55]:
arr2.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
#user input for 2 d array
import numpy as np
list1=[]
list2=[]
n=int(input("Enter the number of elemets of list1 and list2 : "))
# list2=[]
for _ in range(n):
    a=int(input("Enter the number of list1 : "))
    list1.append(a)
for _ in range(n):
    b=int(input("Enter the number of list2 : "))
    list2.append(b)
arr2=np.array([[list1],[list2]])

Enter the number of elemets of list1 and list2 :  6
Enter the number of list1 :  1
Enter the number of list1 :  2
Enter the number of list1 :  3
Enter the number of list1 :  4
Enter the number of list1 :  5
Enter the number of list1 :  6
Enter the number of list2 :  7
Enter the number of list2 :  8
Enter the number of list2 :  9
Enter the number of list2 :  10
Enter the number of list2 :  11
Enter the number of list2 :  12


In [9]:
arr2


array([[[ 1,  2,  3,  4,  5,  6]],

       [[ 7,  8,  9, 10, 11, 12]]])

In [75]:
arr2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [77]:
arr2.ndim

3

In [79]:
arr2.shape

(2, 1, 6)

In [81]:
arr2.size

12

In [83]:
arr2.dtype

dtype('int32')

In [85]:
arr2.itemsize

4

In [87]:
# flatten converting a multidimensional array into a 1 D array
arr3D=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
flattened_array=arr3D.flatten()
flattened_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [98]:
#create a 2D array for the transpose example
list1=[]
list2=[]
n=int(input("Enter the number of elements in a list1 : "))
for _ in range(n):
    a=int(input("Enter the value of list1  : "))
    list1.append(a)
for _ in range(n):
    b=int(input("Enter the value of list2 : "))
    list2.append(b)
arr2=np.array([list1,list2])

Enter the number of elements in a list1 :  6
Enter the value of list1  :  1
Enter the value of list1  :  2
Enter the value of list1  :  3
Enter the value of list1  :  4
Enter the value of list1  :  5
Enter the value of list1  :  6
Enter the value of list2 :  7
Enter the value of list2 :  8
Enter the value of list2 :  9
Enter the value of list2 :  0
Enter the value of list2 :  11
Enter the value of list2 :  12


In [100]:
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9,  0, 11, 12]])

In [102]:
transposed_array=arr2.transpose()

In [104]:
transposed_array

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4,  0],
       [ 5, 11],
       [ 6, 12]])

In [106]:
list3=[]
list4=[]
n=int(input("Enter the number : "))
for _ in range(n):
    a=int(input())
    list3.append(a)
for _ in range(n):
    b=int(input())
    list4.append(b)
arr3=np.array([list3,list4])
print(arr3)

Enter the number :  4
 1
 2
 3
 4
 5
 6
 7
 8


[[1 2 3 4]
 [5 6 7 8]]


In [108]:
arr3.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [114]:
arr4=np.arange(12)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [116]:
arr4.shape

(12,)

In [118]:
arr4.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [120]:
arr4.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [122]:
arr4.shape

(12,)

In [124]:
arr4.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [132]:
temp=[75.2,77.1,74.5,79.3,82.6,81.2,77.8]
arr5=np.array(temp)

arr5

array([75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8])

In [134]:
arr5.ndim

1

In [136]:
arr5.shape

(7,)

In [138]:
arr5.size

7

In [140]:
arr5.dtype

dtype('float64')

In [142]:
arr5.itemsize

8

In [144]:
arr5.data

In [146]:
arr5.reshape(3,2) # we can not reshape because size of the the array is 7 
#and it is no divide equally

ValueError: cannot reshape array of size 7 into shape (3,2)

In [150]:
arr5.flatten()

array([75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8])

In [152]:
arr5.T

array([75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8])

#Arithmetic Operations using Numpy

In [155]:
#Addition
a=np.array([30,20,10])
b=np.array([10,20,30])
print(a)
print(b)
result=np.add(a,b)
print(result)

[30 20 10]
[10 20 30]
[40 40 40]


In [13]:
[1,1,1]+[2,2,2] # addition of lists is a concatenation operation

[1, 1, 1, 2, 2, 2]

In [165]:
#substraction
a=np.array([[30,40,60],[50,70,90]])
b=np.array([[10,20,30],[40,30,80]])
print(a)
print(b)
result=np.subtract(a,b)
print(result)

[[30 40 60]
 [50 70 90]]
[[10 20 30]
 [40 30 80]]
[[20 20 30]
 [10 40 10]]


In [167]:
# Multiplication
a=np.array([30,20,10])
b=np.array([10,20,30])
result=np.multiply(a,b)
print(result)

[300 400 300]


In [169]:
#Division
a=np.array([[1,2,1],[2,2,3]])
b=np.array([3,4,5])
print(a)
print(b)
result=np.divide(a,b)
print(result)

[[1 2 1]
 [2 2 3]]
[3 4 5]
[[0.33333333 0.5        0.2       ]
 [0.66666667 0.5        0.6       ]]


In [171]:
#power
a=[2,2,2,2,2]
b=[2,3,4,5,6]
c=np.power(a,b)
print(c)

[ 4  8 16 32 64]


#Statistical Function in Numpy

In [178]:
#calculating Median,Mean,Standard Deviation And Variance in the Array
arr6=np.array([[4,3,2],[10,1,0],[5,8,24]])
print(np.median(arr6))

4.0


In [180]:
print(np.mean(arr6))

6.333333333333333


In [182]:
print(np.std(arr6))

6.944222218666553


In [184]:
print(np.var(arr6))

48.22222222222222


In [186]:
arr6

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [188]:
np.sort(arr6.flatten())

array([ 0,  1,  2,  3,  4,  5,  8, 10, 24])

In [190]:
np.median(arr6,axis=0)

array([5., 3., 2.])

In [192]:
np.percentile(arr6,50)

4.0

In [3]:
#4d array
import numpy as np
arr_4d = np.array([[[[34, -20, 0, 100, 4.5, 2.3], [-90, 5.9, 2.3, 1, 1, -3]], [[0.1, 0.3, -0.9, 1.1, 1.12, 0.4], [8, 3, 4, 10, -10, 33]]], 
                  [[[14, -21, 10, 11.0, 41.5, 12.3], [-91, 5.91, 2.31, 11, 11, -13]], [[0.11, 10.3, -10.9, 1.11, 11.12, 10.4], [81, 13, 41, 11.0, -10.1, 3.31]]]])
arr_4d

array([[[[ 34.  , -20.  ,   0.  , 100.  ,   4.5 ,   2.3 ],
         [-90.  ,   5.9 ,   2.3 ,   1.  ,   1.  ,  -3.  ]],

        [[  0.1 ,   0.3 ,  -0.9 ,   1.1 ,   1.12,   0.4 ],
         [  8.  ,   3.  ,   4.  ,  10.  , -10.  ,  33.  ]]],


       [[[ 14.  , -21.  ,  10.  ,  11.  ,  41.5 ,  12.3 ],
         [-91.  ,   5.91,   2.31,  11.  ,  11.  , -13.  ]],

        [[  0.11,  10.3 , -10.9 ,   1.11,  11.12,  10.4 ],
         [ 81.  ,  13.  ,  41.  ,  11.  , -10.1 ,   3.31]]]])

In [5]:
arr_4d[1][0]

array([[ 14.  , -21.  ,  10.  ,  11.  ,  41.5 ,  12.3 ],
       [-91.  ,   5.91,   2.31,  11.  ,  11.  , -13.  ]])

In [9]:
arr_4d[1][0][0][-3:]

array([11. , 41.5, 12.3])

In [11]:
arr_4d

array([[[[ 34.  , -20.  ,   0.  , 100.  ,   4.5 ,   2.3 ],
         [-90.  ,   5.9 ,   2.3 ,   1.  ,   1.  ,  -3.  ]],

        [[  0.1 ,   0.3 ,  -0.9 ,   1.1 ,   1.12,   0.4 ],
         [  8.  ,   3.  ,   4.  ,  10.  , -10.  ,  33.  ]]],


       [[[ 14.  , -21.  ,  10.  ,  11.  ,  41.5 ,  12.3 ],
         [-91.  ,   5.91,   2.31,  11.  ,  11.  , -13.  ]],

        [[  0.11,  10.3 , -10.9 ,   1.11,  11.12,  10.4 ],
         [ 81.  ,  13.  ,  41.  ,  11.  , -10.1 ,   3.31]]]])

In [13]:
arr_4d[1][1][0][1:-1]

array([ 10.3 , -10.9 ,   1.11,  11.12])

In [15]:
arr_4d[0][1][1]

array([  8.,   3.,   4.,  10., -10.,  33.])

In [17]:
arr_4d[0][1][1][0::2]

array([  8.,   4., -10.])

In [19]:
arr_4d

array([[[[ 34.  , -20.  ,   0.  , 100.  ,   4.5 ,   2.3 ],
         [-90.  ,   5.9 ,   2.3 ,   1.  ,   1.  ,  -3.  ]],

        [[  0.1 ,   0.3 ,  -0.9 ,   1.1 ,   1.12,   0.4 ],
         [  8.  ,   3.  ,   4.  ,  10.  , -10.  ,  33.  ]]],


       [[[ 14.  , -21.  ,  10.  ,  11.  ,  41.5 ,  12.3 ],
         [-91.  ,   5.91,   2.31,  11.  ,  11.  , -13.  ]],

        [[  0.11,  10.3 , -10.9 ,   1.11,  11.12,  10.4 ],
         [ 81.  ,  13.  ,  41.  ,  11.  , -10.1 ,   3.31]]]])

In [21]:
arr_4d[0]

array([[[ 34.  , -20.  ,   0.  , 100.  ,   4.5 ,   2.3 ],
        [-90.  ,   5.9 ,   2.3 ,   1.  ,   1.  ,  -3.  ]],

       [[  0.1 ,   0.3 ,  -0.9 ,   1.1 ,   1.12,   0.4 ],
        [  8.  ,   3.  ,   4.  ,  10.  , -10.  ,  33.  ]]])

In [23]:
arr_4d[0][0][:2,:-1]

array([[ 34. , -20. ,   0. , 100. ,   4.5],
       [-90. ,   5.9,   2.3,   1. ,   1. ]])

In [25]:
arr_4d[0][0][:2,1::2]

array([[-20. , 100. ,   2.3],
       [  5.9,   1. ,  -3. ]])

In [27]:
arr_4d

array([[[[ 34.  , -20.  ,   0.  , 100.  ,   4.5 ,   2.3 ],
         [-90.  ,   5.9 ,   2.3 ,   1.  ,   1.  ,  -3.  ]],

        [[  0.1 ,   0.3 ,  -0.9 ,   1.1 ,   1.12,   0.4 ],
         [  8.  ,   3.  ,   4.  ,  10.  , -10.  ,  33.  ]]],


       [[[ 14.  , -21.  ,  10.  ,  11.  ,  41.5 ,  12.3 ],
         [-91.  ,   5.91,   2.31,  11.  ,  11.  , -13.  ]],

        [[  0.11,  10.3 , -10.9 ,   1.11,  11.12,  10.4 ],
         [ 81.  ,  13.  ,  41.  ,  11.  , -10.1 ,   3.31]]]])

In [33]:
arr7=np.arange(20)
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
#Slicing for string 
str="Shagan sandhu"
print(str[2:4])

ag


In [37]:
str[:]

'Shagan sandhu'

In [39]:
str[::2]
# if i want that space is not to be counted then how its is possible
# in this case space has been counted 

'Saa adu'

In [1]:
import numpy as np

In [3]:
arr=np.array([10,20,30])
print(arr)

[10 20 30]


In [5]:
arr[0]

10

In [7]:
arr[-1]

30

In [19]:
list1=[]
n=int(input("Enter the number of elements in a list :  "))
for _ in range(n):
    b=int(input("Enter the list number"))
    list1.append(b)
arr=np.array(list1)
print(arr)

Enter the number of elements in a list :   3
Enter the list number 1
Enter the list number 2
Enter the list number 3


[1 2 3]


In [25]:
list1=[]
n=int(input("Enter the number of elements in a list : "))
for _ in range(n):
    a=int(input("Enter the element of a : "))
    list1.append(a)
list2=[]
for _ in range(n):
    b=int(input("Enter the element of b : "))
    list2.append(b)
arr1=np.array([list1,list2])
print(arr1)

Enter the number of elements in a list :  4
Enter the element of a :  1
Enter the element of a :  2
Enter the element of a :  3
Enter the element of a :  4
Enter the element of b :  5
Enter the element of b :  6
Enter the element of b :  7
Enter the element of b :  8


[[1 2 3 4]
 [5 6 7 8]]


In [27]:
arr1[0]

array([1, 2, 3, 4])

In [29]:
arr1[1]

array([5, 6, 7, 8])

In [37]:
arr1[1][-2]

7

In [49]:
arr1[0][:1]

array([1])

In [59]:
arr1[0][1:-1:2]

array([2])

In [63]:
# dimension 
#1d array
arr=np.array([10,20,30])
arr

array([10, 20, 30])

In [65]:
#2d dimension
arr=np.array([[10,20,30],[40,50,60]])
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [69]:
#3d dimension
arr=np.array([[[10,20,30],[40,50,60],[70,80,90]]])
arr

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [71]:
arr[0]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [79]:
arr[0][1][-2]

50

In [81]:
arr.ndim

3

#Attributes and function of numpy

In [86]:
list1=[]
n=int(input("Enter the number of elements in a list : "))
list2=[]
list3=[]
for _ in range(n):
    a=int(input("enter the element of a : "))
    list1.append(a)
for _ in range(n):
    b=int(input("Enter the element of b : "))
    list2.append(b)
for _ in range(n):
    c=int(input("Enter the element of c : "))
    list3.append(c)
arr2=np.array([list1,list2,list3])
arr2

Enter the number of elements in a list :  4
enter the element of a :  1
enter the element of a :  2
enter the element of a :  3
enter the element of a :  4
Enter the element of b :  5
Enter the element of b :  6
Enter the element of b :  7
Enter the element of b :  8
Enter the element of c :  9
Enter the element of c :  10
Enter the element of c :  11
Enter the element of c :  12


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
arr2[0]

array([1, 2, 3, 4])

In [96]:
arr2.ndim

2

In [98]:
arr2.size

12

In [100]:
arr2.shape

(3, 4)

In [102]:
#Size of an array in bytes
arr2.dtype

dtype('int32')

In [108]:
arr2.itemsize

4

In [110]:
arr2.data

In [112]:
arr2.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [114]:
arr2.T.shape

(4, 3)

In [120]:
#convert 2d array to 1d array
arr2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [122]:
arr2.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [124]:
arr2.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [126]:
arr2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [128]:
arr2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [136]:
arr3=np.arange(1,21)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [140]:
arr3.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [142]:
arr3.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [144]:
arr3.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [156]:
#practice question
temp=[75.2,77.1,74.5,79.3,82.6,81.2,77.8]
arr4=np.array(temp)
print("n dimension : ",arr4.ndim)
print("Size : ",arr4.size)
print("data : ",arr4.data)
print("itemsize:  ",arr4.itemsize)
print("shape : ",arr4.shape)
print("Transpose : ",arr4.T)
print("Flatten : ",arr4.flatten())
#reshape cannot be done because it is an odd numbers

n dimension :  1
Size :  7
data :  <memory at 0x000001DFEB925E40>
itemsize:   8
shape :  (7,)
Transpose :  [75.2 77.1 74.5 79.3 82.6 81.2 77.8]
Flatten :  [75.2 77.1 74.5 79.3 82.6 81.2 77.8]


#Statistical and arithemetic operation

In [160]:
list1=[]
list2=[]
list3=[]
list4=[]
n=int(input("Enter the number of elements : "))
for _ in range(n):
    a=int(input("Enter the value of a : "))
    list1.append(a)
for _ in range(n):
    b=int(input("Enter the value of b : "))
    list2.append(b)
for _ in range(n):
    c=int(input("Enter the value of c : "))
    list3.append(c)
for _ in range(n):
    d=int(input("Enter the value of d : "))
    list4.append(d)
arr6=np.array([list1,list2,list3,list4])
arr6

Enter the number of elements :  3
Enter the value of a :  1
Enter the value of a :  2
Enter the value of a :  3
Enter the value of b :  4
Enter the value of b :  5
Enter the value of b :  6
Enter the value of c :  7
Enter the value of c :  8
Enter the value of c :  9
Enter the value of d :  10
Enter the value of d :  11
Enter the value of d :  12


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [182]:
a=np.array([10,20,30])
b=np.array([40,50,60])
result=np.add(a,b)
print(result)

[50 70 90]


In [166]:
result1=np.subtract(a,b)
result2=np.subtract(b,a)
print(result1)
print(result2)

[-30 -30 -30]
[30 30 30]


In [168]:
result=np.multiply(a,b)
print(result)

[ 400 1000 1800]


In [176]:
result=np.divide(a,b)
print(result)

[[2. 2. 2.]
 [2. 2. 2.]]


In [188]:
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[5,10,15],[20,25,30]])
result=np.subtract(a,b)
print(result)


[[ 5 10 15]
 [20 25 30]]


In [190]:
result=np.power(a,b)
print(result)

[[     100000   797966336 -2080931840]
 [          0 -1308622848           0]]


In [192]:
a=[2,2,2,2,2]
b=[2,3,4,5,6]
result=np.power(a,b)
print(result)

[ 4  8 16 32 64]


# Statistical

In [198]:
#Median
list1=[]
list2=[]
n=int(input("Enter the value of n : "))
for _ in range(n):
    a=int(input("enter the the value of a : "))
    list1.append(a)
for _ in range(n):
    b=int(input("enter the value of b : "))
    list2.append(b)
arr1=np.array([list1,list2])
print(arr1)

Enter the value of n :  4
enter the the value of a :  1
enter the the value of a :  2
enter the the value of a :  3
enter the the value of a :  4
enter the value of b :  5
enter the value of b :  6
enter the value of b :  7
enter the value of b :  8


[[1 2 3 4]
 [5 6 7 8]]


In [200]:
arr1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [204]:
np.median(arr1)

4.5

In [206]:
#coulumnwise solve 
np.median(arr1,axis=0)

array([3., 4., 5., 6.])

In [208]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [210]:
#rowwise
np.median(arr1,axis=1)

array([2.5, 6.5])

In [212]:
#Mean
np.mean(arr1)

4.5

In [214]:
np.mean(arr1, axis=0)

array([3., 4., 5., 6.])

In [216]:
np.mean(arr1,axis=1)

array([2.5, 6.5])

In [218]:
np.std(arr1)

2.29128784747792

In [220]:
np.var(arr1)

5.25

In [224]:
#calculating percentile
print([np.percentile(arr1,i) for i in range(101)])

[1.0, 1.07, 1.1400000000000001, 1.21, 1.28, 1.35, 1.42, 1.49, 1.56, 1.63, 1.7000000000000002, 1.77, 1.8399999999999999, 1.9100000000000001, 1.98, 2.05, 2.12, 2.1900000000000004, 2.26, 2.33, 2.4000000000000004, 2.4699999999999998, 2.54, 2.6100000000000003, 2.6799999999999997, 2.75, 2.8200000000000003, 2.89, 2.96, 3.03, 3.1, 3.17, 3.24, 3.31, 3.3800000000000003, 3.4499999999999997, 3.52, 3.59, 3.66, 3.73, 3.8000000000000003, 3.8699999999999997, 3.94, 4.01, 4.08, 4.15, 4.220000000000001, 4.29, 4.359999999999999, 4.43, 4.5, 4.57, 4.640000000000001, 4.71, 4.78, 4.8500000000000005, 4.92, 4.99, 5.06, 5.13, 5.2, 5.27, 5.34, 5.41, 5.48, 5.55, 5.62, 5.69, 5.760000000000001, 5.83, 5.8999999999999995, 5.97, 6.04, 6.109999999999999, 6.18, 6.25, 6.32, 6.390000000000001, 6.46, 6.53, 6.6000000000000005, 6.67, 6.739999999999999, 6.81, 6.88, 6.95, 7.02, 7.09, 7.16, 7.23, 7.3, 7.37, 7.44, 7.510000000000001, 7.58, 7.6499999999999995, 7.72, 7.79, 7.859999999999999, 7.93, 8.0]


#String function in numpy

In [227]:
a=["hello","world"]
b=["keep","Learning"]
c=np.char.add(a,b)
print(c)

['hellokeep' 'worldLearning']


In [233]:
#Replacing the old substring to new substring
a=["hi how r u?"]
print(a)
c=np.char.replace(a,"hi","hlo")
print(c)

['hi how r u?']
['hlo how r u?']


In [237]:
#converting all of them in upper case or lower case
a=["hello everyone"]
print(np.char.upper(a))
b=["HEY HOW ARE YOU !"]
print(np.char.lower(b))

['HELLO EVERYONE']
['hey how are you !']


#Indexing

In [240]:
import numpy as np
arr_4d = np.array([[[[34, -20, 0, 100, 4.5, 2.3], [-90, 5.9, 2.3, 1, 1, -3]], [[0.1, 0.3, -0.9, 1.1, 1.12, 0.4], [8, 3, 4, 10, -10, 33]]], 
                  [[[14, -21, 10, 11.0, 41.5, 12.3], [-91, 5.91, 2.31, 11, 11, -13]], [[0.11, 10.3, -10.9, 1.11, 11.12, 10.4], [81, 13, 41, 11.0, -10.1, 3.31]]]])
arr_4d

array([[[[ 34.  , -20.  ,   0.  , 100.  ,   4.5 ,   2.3 ],
         [-90.  ,   5.9 ,   2.3 ,   1.  ,   1.  ,  -3.  ]],

        [[  0.1 ,   0.3 ,  -0.9 ,   1.1 ,   1.12,   0.4 ],
         [  8.  ,   3.  ,   4.  ,  10.  , -10.  ,  33.  ]]],


       [[[ 14.  , -21.  ,  10.  ,  11.  ,  41.5 ,  12.3 ],
         [-91.  ,   5.91,   2.31,  11.  ,  11.  , -13.  ]],

        [[  0.11,  10.3 , -10.9 ,   1.11,  11.12,  10.4 ],
         [ 81.  ,  13.  ,  41.  ,  11.  , -10.1 ,   3.31]]]])

In [242]:
arr_4d.ndim

4

In [250]:
arr_4d[1][0][0][-3]

11.0

In [252]:
arr_4d[1][1][1][-1]

3.31